console.log("Hello");
$('#contactus').on('click',function(){
    $('.section_contact').addClass('section_contact_active');
    $('.section_home').removeClass('section_home_active');
    $('.section_footer').removeClass('section_footer_active')
})
$('#home').on('click',function(){
    $('.section_home').addClass('section_home_active');
    $('.section_contact').removeClass('section_contact_active');
    $('.section_footer').removeClass('section_footer_active')
})
$('#footer').on('click',function(){
    $('.section_footer').addClass('section_footer_active')
    $('.section_home').removeClass('section_home_active');
    $('.section_contact').removeClass('section_contact_active');
})